import { v4 as uuid } from "uuid";
export const Books = [
  {
    id: uuid(),
    img: "https://m.media-amazon.com/images/I/51bVNTqHFlL._AC_UL400_.jpg",
    name: "The Alchemist",
    author: "Paulo Coelho ",
    type: "want",
    categoryTitle: "Fiction",
  },
  {
    id: uuid(),
    img: "https://rukminim1.flixcart.com/image/612/612/jpu324w0/book/0/9/0/believe-in-yourself-original-imafbzz2h7yfg5zz.jpeg?q=70",
    name: "Believe In Yourself",
    author: "Joseph",
    type: "none",
    categoryTitle: "Self Help",
  },
  {
    id: uuid(),
    img: "https://rukminim1.flixcart.com/image/612/612/kokdci80/regionalbooks/t/x/c/zero-to-one-original-imag2zzngtfasecu.jpeg?q=70",
    name: "Zero To One",
    author: "Peter Thiel",
    type: "want",
    categoryTitle: "Fiction",
  },
  {
    id: uuid(),
    img: "https://rukminim1.flixcart.com/image/612/612/kufuikw0/book/x/s/w/atomic-habits-original-imag7kbzg2fu8rjv.jpeg?q=70",
    name: "Atomic Habits",
    author: "James Clear",
    type: "want",
    categoryTitle: "Self Help",
  },
  {
    id: uuid(),
    img: "https://rukminim1.flixcart.com/image/612/612/kwxv98w0/book/l/z/y/do-epic-shit-original-imag9gcfcwfvwtep.jpeg?q=70",
    name: "Do Epic Shit",
    author: "Ankur Warikoo",
    type: "reading",
    categoryTitle: "Self Help",
  },

  {
    id: uuid(),
    img: "https://rukminim1.flixcart.com/image/612/612/kufuikw0/book/0/6/q/ikigai-original-imag7kc7q5ugy2km.jpeg?q=70",
    name: "IKIGAI",
    author: "Hector Garcia",
    type: "reading",
    categoryTitle: "Non-Fiction",
  },
  {
    id: uuid(),
    img: "https://rukminim1.flixcart.com/image/612/612/kgwld3k0/book/1/9/4/rich-dad-poor-dad-original-imafxf885pytvycy.jpeg?q=70",
    name: "Rich Dad Poor Dad",
    author: "Robert Kiyoski",
    type: "none",
    categoryTitle: "Non-Fiction",
  },
  {
    id: uuid(),
    img: "https://rukminim1.flixcart.com/image/612/612/kirr24w0-0/book/k/k/g/the-monk-who-sold-his-ferrari-original-imafyhgacv9jrgv7.jpeg?q=70",
    name: "Monk Who Sold His Ferrari",
    author: "Robin Sharma",
    type: "reading",
    categoryTitle: "Non-Fiction",
  },
  {
    id: uuid(),
    img: "https://rukminim1.flixcart.com/image/612/612/ki96c280-0/book/3/p/n/one-indian-girl-original-imafy2zrymfbtygz.jpeg?q=70",
    name: "One Indian Girl",
    author: "Chetan Bhagat",
    type: "read",
    categoryTitle: "Fiction",
  },
  {
    id: uuid(),
    img: "https://rukminim1.flixcart.com/image/612/612/kjbr8280-0/book/z/r/9/learning-how-to-fly-original-imafyx6zuhvfhv94.jpeg?q=70",
    name: "Learning How To Fly",
    author: "A.P.J Abdul Kalam",
    type: "none",
    categoryTitle: "Fiction",
  },
  {
    id: uuid(),
    img: "https://rukminim1.flixcart.com/image/612/612/kwpam4w0/book/r/a/r/-original-imag9bv6bzstsjgk.jpeg?q=70",
    name: "400 Days",
    author: "Chetan Bhagat",
    type: "read",
    categoryTitle: "Self Help",
  },
  {
    id: uuid(),
    img: "https://m.media-amazon.com/images/I/41yu2qXhXXL._SX324_BO1,204,203,200_.jpg",
    name: "Sapiens",
    author: "Yuval Noah Harari",
    type: "read",
    categoryTitle: "Non-Fiction",
  },
];
